# Generated by Django 5.2.1 on 2025-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('post_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_policy', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('selling', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle_features', models.TextField(blank=True, null=True)),
                ('posting_time', models.DateTimeField(blank=True, null=True)),
                ('image_links', models.TextField(blank=True, null=True)),
                ('post_link', models.URLField(blank=True, null=True)),
                ('comment_link', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('kilometers_used', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_policy', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('engine_capacity', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_ratings', models.IntegerField(blank=True, null=True)),
                ('on_time', models.BooleanField(default=False)),
                ('polite_friendly_communication', models.BooleanField(default=False)),
                ('reliable', models.BooleanField(default=False)),
                ('accurate_product_description', models.BooleanField(default=False)),
                ('product_quality_good', models.BooleanField(default=False)),
                ('good_price_product', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('fast_message_response', models.BooleanField(default=False)),
                ('reasonable_price_negotiation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
