# Generated by Django 5.2.1 on 2025-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_alter_vehicle_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='num_ratings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='selling',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
