# Generated by Django 5.2.1 on 2025-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_alter_vehicle_num_ratings_alter_vehicle_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='accurate_product_description',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='comment_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fast_message_response',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='good_price_product',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_links',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='on_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='polite_friendly_communication',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='post_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='posting_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='product_quality_good',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reasonable_price_negotiation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reliable',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller_policy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_features',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warranty_policy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
